--
-- PostgreSQL database dump
--

-- Dumped from database version 11.8 (Debian 11.8-1.pgdg90+1)
-- Dumped by pg_dump version 12.4

-- Started on 2020-10-19 09:07:43

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 11 (class 2615 OID 318142)
-- Name: qgis; Type: SCHEMA; Schema: -; Owner: oiv_admin
--

CREATE SCHEMA qgis;


ALTER SCHEMA qgis OWNER TO oiv_admin;

--
-- TOC entry 4746 (class 0 OID 0)
-- Dependencies: 11
-- Name: SCHEMA qgis; Type: COMMENT; Schema: -; Owner: oiv_admin
--

COMMENT ON SCHEMA qgis IS 'Schema voor applicatie qgis';


--
-- TOC entry 2042 (class 1247 OID 318211)
-- Name: eindstijl_type; Type: TYPE; Schema: qgis; Owner: oiv_admin
--

CREATE TYPE qgis.eindstijl_type AS ENUM (
    'square',
    'flat',
    'round'
);


ALTER TYPE qgis.eindstijl_type OWNER TO oiv_admin;

--
-- TOC entry 2035 (class 1247 OID 318218)
-- Name: lijnstijl_type; Type: TYPE; Schema: qgis; Owner: oiv_admin
--

CREATE TYPE qgis.lijnstijl_type AS ENUM (
    'no',
    'solid',
    'dash',
    'dot',
    'dash dot',
    'dash dot dot'
);


ALTER TYPE qgis.lijnstijl_type OWNER TO oiv_admin;

--
-- TOC entry 2038 (class 1247 OID 318232)
-- Name: verbindingsstijl_type; Type: TYPE; Schema: qgis; Owner: oiv_admin
--

CREATE TYPE qgis.verbindingsstijl_type AS ENUM (
    'bevel',
    'miter',
    'round'
);


ALTER TYPE qgis.verbindingsstijl_type OWNER TO oiv_admin;

--
-- TOC entry 2045 (class 1247 OID 318240)
-- Name: vulstijl_type; Type: TYPE; Schema: qgis; Owner: oiv_admin
--

CREATE TYPE qgis.vulstijl_type AS ENUM (
    'solid',
    'horizontal',
    'vertical',
    'cross',
    'b_diagonal',
    'f_diagonal',
    'diagonal_x',
    'dense1',
    'dense2',
    'dense3',
    'dense4',
    'dense5',
    'dense6',
    'dense7',
    'no'
);


ALTER TYPE qgis.vulstijl_type OWNER TO oiv_admin;

SET default_tablespace = '';

--
-- TOC entry 326 (class 1259 OID 319593)
-- Name: grid; Type: TABLE; Schema: qgis; Owner: oiv_admin
--

CREATE TABLE qgis.grid (
    id integer NOT NULL,
    geom public.geometry(MultiPolygon,28992),
    datum_aangemaakt timestamp with time zone DEFAULT now(),
    datum_gewijzigd timestamp with time zone,
    y_as_label text,
    x_as_label text,
    afstand integer,
    object_id integer,
    vaknummer character varying(10)
);


ALTER TABLE qgis.grid OWNER TO oiv_admin;

--
-- TOC entry 325 (class 1259 OID 319591)
-- Name: grid_id_seq; Type: SEQUENCE; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE qgis.grid ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME qgis.grid_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 324 (class 1259 OID 319573)
-- Name: isolijnen; Type: TABLE; Schema: qgis; Owner: oiv_admin
--

CREATE TABLE qgis.isolijnen (
    id integer NOT NULL,
    geom public.geometry(LineString,28992),
    datum_aangemaakt timestamp with time zone DEFAULT now(),
    datum_gewijzigd timestamp with time zone,
    hoogte smallint,
    omschrijving text,
    object_id integer
);


ALTER TABLE qgis.isolijnen OWNER TO oiv_admin;

--
-- TOC entry 323 (class 1259 OID 319571)
-- Name: isolijnen_id_seq; Type: SEQUENCE; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE qgis.isolijnen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME qgis.isolijnen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 318208)
-- Name: styles_id_seq; Type: SEQUENCE; Schema: qgis; Owner: oiv_admin
--

CREATE SEQUENCE qgis.styles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1;


ALTER TABLE qgis.styles_id_seq OWNER TO oiv_admin;

--
-- TOC entry 228 (class 1259 OID 318271)
-- Name: styles; Type: TABLE; Schema: qgis; Owner: oiv_admin
--

CREATE TABLE qgis.styles (
    id integer DEFAULT nextval('qgis.styles_id_seq'::regclass) NOT NULL,
    laagnaam character varying(100),
    soortnaam character varying(100),
    lijndikte numeric,
    lijnkleur character varying(9),
    lijnstijl qgis.lijnstijl_type,
    vulkleur character varying(9),
    vulstijl qgis.vulstijl_type,
    verbindingsstijl qgis.verbindingsstijl_type,
    eindstijl qgis.eindstijl_type
);


ALTER TABLE qgis.styles OWNER TO oiv_admin;

--
-- TOC entry 229 (class 1259 OID 318282)
-- Name: styles_symbols_type; Type: TABLE; Schema: qgis; Owner: oiv_admin
--

CREATE TABLE qgis.styles_symbols_type (
    naam text NOT NULL,
    size integer,
    symbol_name text
);


ALTER TABLE qgis.styles_symbols_type OWNER TO oiv_admin;

--
-- TOC entry 349 (class 1259 OID 319765)
-- Name: view_bouwlagen; Type: VIEW; Schema: qgis; Owner: oiv_admin
--

CREATE VIEW qgis.view_bouwlagen AS
 SELECT bl.id,
    bl.geom,
    bl.datum_aangemaakt,
    bl.datum_gewijzigd,
    bl.bouwlaag,
    bl.bouwdeel,
    o.id AS object_id,
    o.formelenaam,
    o.status
   FROM (objecten.bouwlagen bl
     JOIN objecten.object o ON ((bl.id = o.id)))
  WHERE ((((o.status)::text = 'in gebruik'::text) AND (o.datum_geldig_vanaf <= now())) OR ((o.datum_geldig_vanaf IS NULL) AND (o.datum_geldig_tot > now())) OR (o.datum_geldig_tot IS NULL));


ALTER TABLE qgis.view_bouwlagen OWNER TO oiv_admin;

--
-- TOC entry 4740 (class 0 OID 319593)
-- Dependencies: 326
-- Data for Name: grid; Type: TABLE DATA; Schema: qgis; Owner: oiv_admin
--

COPY qgis.grid (id, geom, datum_aangemaakt, datum_gewijzigd, y_as_label, x_as_label, afstand, object_id, vaknummer) FROM stdin;
\.


--
-- TOC entry 4738 (class 0 OID 319573)
-- Dependencies: 324
-- Data for Name: isolijnen; Type: TABLE DATA; Schema: qgis; Owner: oiv_admin
--

COPY qgis.isolijnen (id, geom, datum_aangemaakt, datum_gewijzigd, hoogte, omschrijving, object_id) FROM stdin;
\.


--
-- TOC entry 4735 (class 0 OID 318271)
-- Dependencies: 228
-- Data for Name: styles; Type: TABLE DATA; Schema: qgis; Owner: oiv_admin
--

COPY qgis.styles (id, laagnaam, soortnaam, lijndikte, lijnkleur, lijnstijl, vulkleur, vulstijl, verbindingsstijl, eindstijl) FROM stdin;
\.


--
-- TOC entry 4736 (class 0 OID 318282)
-- Dependencies: 229
-- Data for Name: styles_symbols_type; Type: TABLE DATA; Schema: qgis; Owner: oiv_admin
--

COPY qgis.styles_symbols_type (naam, size, symbol_name) FROM stdin;
\.


--
-- TOC entry 4749 (class 0 OID 0)
-- Dependencies: 325
-- Name: grid_id_seq; Type: SEQUENCE SET; Schema: qgis; Owner: oiv_admin
--

SELECT pg_catalog.setval('qgis.grid_id_seq', 1, false);


--
-- TOC entry 4750 (class 0 OID 0)
-- Dependencies: 323
-- Name: isolijnen_id_seq; Type: SEQUENCE SET; Schema: qgis; Owner: oiv_admin
--

SELECT pg_catalog.setval('qgis.isolijnen_id_seq', 1, false);


--
-- TOC entry 4751 (class 0 OID 0)
-- Dependencies: 227
-- Name: styles_id_seq; Type: SEQUENCE SET; Schema: qgis; Owner: oiv_admin
--

SELECT pg_catalog.setval('qgis.styles_id_seq', 1, false);


--
-- TOC entry 4598 (class 2606 OID 319601)
-- Name: grid grid_pkey; Type: CONSTRAINT; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE ONLY qgis.grid
    ADD CONSTRAINT grid_pkey PRIMARY KEY (id);


--
-- TOC entry 4595 (class 2606 OID 319581)
-- Name: isolijnen isolijnen_pkey; Type: CONSTRAINT; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE ONLY qgis.isolijnen
    ADD CONSTRAINT isolijnen_pkey PRIMARY KEY (id);


--
-- TOC entry 4588 (class 2606 OID 318279)
-- Name: styles styles_pkey; Type: CONSTRAINT; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE ONLY qgis.styles
    ADD CONSTRAINT styles_pkey PRIMARY KEY (id);


--
-- TOC entry 4590 (class 2606 OID 318281)
-- Name: styles styles_soortnaam_key; Type: CONSTRAINT; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE ONLY qgis.styles
    ADD CONSTRAINT styles_soortnaam_key UNIQUE (soortnaam);


--
-- TOC entry 4592 (class 2606 OID 318289)
-- Name: styles_symbols_type styles_symbols_type_pkey; Type: CONSTRAINT; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE ONLY qgis.styles_symbols_type
    ADD CONSTRAINT styles_symbols_type_pkey PRIMARY KEY (naam);


--
-- TOC entry 4596 (class 1259 OID 319607)
-- Name: grid_geom_gist; Type: INDEX; Schema: qgis; Owner: oiv_admin
--

CREATE INDEX grid_geom_gist ON qgis.grid USING gist (geom);


--
-- TOC entry 4593 (class 1259 OID 319587)
-- Name: isolijnen_geom_gist; Type: INDEX; Schema: qgis; Owner: oiv_admin
--

CREATE INDEX isolijnen_geom_gist ON qgis.isolijnen USING gist (geom);


--
-- TOC entry 4603 (class 2620 OID 319608)
-- Name: grid trg_set_insert; Type: TRIGGER; Schema: qgis; Owner: oiv_admin
--

CREATE TRIGGER trg_set_insert BEFORE INSERT ON qgis.grid FOR EACH ROW EXECUTE PROCEDURE objecten.set_timestamp('datum_aangemaakt');


--
-- TOC entry 4601 (class 2620 OID 319588)
-- Name: isolijnen trg_set_insert; Type: TRIGGER; Schema: qgis; Owner: oiv_admin
--

CREATE TRIGGER trg_set_insert BEFORE INSERT ON qgis.isolijnen FOR EACH ROW EXECUTE PROCEDURE objecten.set_timestamp('datum_aangemaakt');


--
-- TOC entry 4604 (class 2620 OID 319609)
-- Name: grid trg_set_mutatie; Type: TRIGGER; Schema: qgis; Owner: oiv_admin
--

CREATE TRIGGER trg_set_mutatie BEFORE UPDATE ON qgis.grid FOR EACH ROW EXECUTE PROCEDURE objecten.set_timestamp('datum_gewijzigd');


--
-- TOC entry 4602 (class 2620 OID 319589)
-- Name: isolijnen trg_set_mutatie; Type: TRIGGER; Schema: qgis; Owner: oiv_admin
--

CREATE TRIGGER trg_set_mutatie BEFORE UPDATE ON qgis.isolijnen FOR EACH ROW EXECUTE PROCEDURE objecten.set_timestamp('datum_gewijzigd');


--
-- TOC entry 4600 (class 2606 OID 319602)
-- Name: grid grid_object_id_fk; Type: FK CONSTRAINT; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE ONLY qgis.grid
    ADD CONSTRAINT grid_object_id_fk FOREIGN KEY (object_id) REFERENCES objecten.object(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4599 (class 2606 OID 319582)
-- Name: isolijnen isolijnen_object_id_fk; Type: FK CONSTRAINT; Schema: qgis; Owner: oiv_admin
--

ALTER TABLE ONLY qgis.isolijnen
    ADD CONSTRAINT isolijnen_object_id_fk FOREIGN KEY (object_id) REFERENCES objecten.object(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4747 (class 0 OID 0)
-- Dependencies: 324
-- Name: TABLE isolijnen; Type: ACL; Schema: qgis; Owner: oiv_admin
--

GRANT SELECT ON TABLE qgis.isolijnen TO oiv_read;
GRANT INSERT,DELETE,UPDATE ON TABLE qgis.isolijnen TO oiv_write;


--
-- TOC entry 4748 (class 0 OID 0)
-- Dependencies: 349
-- Name: TABLE view_bouwlagen; Type: ACL; Schema: qgis; Owner: oiv_admin
--

GRANT SELECT ON TABLE qgis.view_bouwlagen TO oiv_read;
GRANT INSERT,DELETE,UPDATE ON TABLE qgis.view_bouwlagen TO oiv_write;


-- Completed on 2020-10-19 09:07:45

--
-- PostgreSQL database dump complete
--

